# Generated by Django 5.0.6 on 2024-07-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=1500),
        ),
    ]
