# Generated by Django 5.0.6 on 2024-07-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0002_alter_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='_question_order',
        ),
    ]
