# Generated by Django 5.0.6 on 2024-07-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_generator', '0003_remove_test__question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
